### ISSUE TITLE
Confirm MRW_ENHANCED_GROUPING_NO_MIRRORING is set correctly.

### ISSUE THREAD

**Issue by williamspatrick** [open-power/barreleye-xml#6]
See open-power/op-build#493 .

**Comment by williamspatrick** [comment]
@johnhihi - Please check into this.  @bwmashak may have more details.

**Comment by johnhihi** [comment]
Hi @bwmashak.
Is that we just put MRW_ENHANCED_GROUPING_NO_MIRRORING to false?

**Comment by bwmashak** [comment]
Yes put MRW_ENHANCED_GROUPING_NO_MIRRORING to false.

**Comment by johnhihi** [comment]
Yes, the value of MRW_ENHANCED_GROUPING_NO_MIRRORING is set to false.
We could close this.
@williamspatrick and @bwmashak , thank you.

**Comment by ghost** [comment]
As per @johnhihi , closing defect (I also checked was set to false)

**Comment by ghost** [comment]
Doh - I don't actually have the rights to close the defect. Could somebody with the magic button present please press close?
